trigger: none

pr:
- develop

pool:
  vmImage: 'windows-2019'

steps:
  # Azure Key Vault
  # Download Azure Key Vault secrets
  - task: AzureKeyVault@1
    inputs:
      azureSubscription: 'hazzat-api-ppe - Azure'
      keyVaultName: 'hazzat-api-ppe'
      secretsFilter: 'hazzat-db-ro-connectionString'

  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: custom
      workingDir: src
      verbose: false
      customCommand: 'install'

  - task: Npm@1
    displayName: 'npm build'
    inputs:
      command: custom
      workingDir: src
      verbose: false
      customCommand: 'run build'

  - task: Npm@1
    displayName: 'Unit Tests'
    inputs:
      command: custom
      workingDir: src
      verbose: false
      customCommand: 'run test-unit'


  - task: Npm@1
    displayName: 'Integration Tests'
    inputs:
      command: custom
      workingDir: src
      verbose: false
      customCommand: 'run test-int'
    env:
      CUSTOMCONNSTR_DBCONNECTIONSTRING: $(hazzat-db-ro-connectionString)

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/testResults*.trx'
      failTaskOnFailedTests: false
